version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - app-network
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-network
  mariadb:
    build: ./mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - app-network
  ftp:
    build: ./ftp
    ports:
      - "20:20"
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
    networks:
      - app-network
  wordpress:
    build: ./wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
