version: '3.8'

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - nginx_logs:/var/log/nginx
    networks:
      - frontend
      - backend
    depends_on:
      - wordpress
      - adminer
    restart: unless-stopped

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: unless-stopped
    command: mysqld --skip-grant-tables


  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
      - frontend
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    ports:
      - "9000:9000"

  redis:
    build: ./srcs/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped

  ftp:
    build: ./srcs/ftp
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110/tcp"
    volumes:
      - ftp_data:/home/anporced/data/ftp
    networks:
      - backend
    restart: unless-stopped

  static:
    build: ./srcs/static
    container_name: static
    ports:
      - "8080:8080"
    volumes:
      - static_data:/var/www/html
    networks:
      - frontend
    restart: unless-stopped

  adminer:
    build: ./srcs/adminer
    container_name: adminer
    ports:
      - "8081:8081"
    volumes:
      - adminer_data:/var/www/html
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  nginx_logs:
  mariadb_data:
  wordpress_data:
  redis_data:
  ftp_data:
  static_data:
  adminer_data:
